---
title: "Curso de Verão 2016 - Lab 01"
author: "Ralf Lima da Costa"
date: "`r Sys.Date()`"
output: html_document
---


# Curso de Verão 2016 - Lab 01

## Funções

```{r}
moeda <- function(p){
    x <- runif(1)
    if (x < p){
        return(1)
    }else{
        return(0)
    }
}

moedas <- function(p,n){
    x <- integer(length = n)
    for (i in 1:n){
        x[i] <- moeda(p)
    }
    return(x)
}

proporcao <- function(resultados){
    v1 <- length(resultados[resultados==1])
    v0 <- length(resultados[resultados==0])
    if (v0==0){
        return(1)
    }else{
        return(v1/(v1+v0))
    }
}

simulacao <- function(k,n,p){
    x <- numeric(length = k)
    for (i in 1:k){
        x[i] <- proporcao(moedas(p,n))
    }
    return(x)
}
```

## Simulações Executadas

```{r}
hist(simulacao(k = 10, n = 10, p = 0.5))

hist(simulacao(k = 100, n = 10, p = 0.5))

hist(simulacao(k = 1000, n = 10, p = 0.5))

hist(simulacao(k = 1000, n = 20, p = 0.5))

hist(simulacao(k = 1000, n = 20, p = 0.7))

hist(simulacao(k = 1000, n = 20, p = 0.3))

```

