---
title: "Curso de Verão 2016 - Lab 04"
author: "Ralf Lima da Costa"
date: "`r Sys.Date()`"
output: html_document
---

```{r, results='hide', warning=FALSE}
library(magrittr)
library(ggplot2)
```

##Geom_Point

1. Os aspectos estéticos obrigatórios são x e y.

2.
```{r}
diamonds %>%
    ggplot() +
    geom_point(aes(price, carat)) +
    xlab("Price") +
    ylab("Carat")
```

3.
```{r}
diamonds %>%
    ggplot(aes(price, carat)) +
    geom_point() +
    xlab("Price") +
    ylab("Carat") +
    facet_wrap(~clarity)
```


##Geom_Histogram

4. O aspecto estético obrigatório é x.

5.
```{r, warning=FALSE, error=FALSE, message=FALSE}
diamonds %>%
    ggplot(aes(x=price)) +
    geom_histogram(colour = "white", fill = "blue")

```

6.
```{r, warning=FALSE, error=FALSE, message=FALSE}
diamonds %>%
    ggplot(aes(x=price)) +
    geom_histogram(aes(y=..density..),colour = "white", fill = "blue") +
    geom_density(alpha=.5, fill="yellow")
```

##Geom_Boxplot

7. Os aspectos estéticos obrigátorios são lower, middle, upper, x, ymax, ymin.

8.
```{r}
diamonds %>%
    ggplot(aes(x=price)) +
    geom_boxplot(aes(x=cut, color=cut, y=price)) +
    xlab("Cut") +
    ylab("Price")
```

9.
```{r}
diamonds %>%
    ggplot(aes(x=cut, y=price, color=cut)) +
    geom_boxplot() +
    scale_color_manual(values = c("yellow","orange","red","brown","black")) +
    xlab("Cut") +
    ylab("Price")
```

##Geom_Bar

10. O aspecto estético obrigatório é x.

11.
```{r}
diamonds %>%
    ggplot(aes(x=color)) +
    geom_bar(fill="gray")
```

##Outras Bases de Dados

12.
```{r, results='hide', warning=FALSE, error=FALSE, message=FALSE}
library(dplyr)
library(tidyr)
library(lubridate)
```

```{r}
economics %>%
    ggplot(aes(x = unemploy, y = uempmed)) +
    geom_point() +
    labs(x = "Desempregados", y="Tempo Medio de Desemprego")
```

13.
```{r}
economics %>%
    ggplot(aes(x = unemploy, y = uempmed)) +
    geom_point(aes(color=year(date))) +
    labs(x = "Desempregados", y="Tempo Medio de Desemprego")
```

14.
```{r}
economics %>%
    ggplot(aes(x = date, y=unemploy)) +
    geom_line()
```

15.
```{r}
economics %>%
    select(unemploy, date) %>%
    mutate(ano=year(date)) %>%
    group_by(ano) %>%
    summarise(unemploy_med = mean(unemploy)) %>%
    ungroup() %>%
    ggplot(aes(x = ano, y=unemploy_med)) +
    geom_line() +
    labs(x = "Ano", y = "Média de Desempregados")
```

16.
```{r}
economics %>%
    select(unemploy, date) %>%
    mutate(ano=year(date)) %>%
    group_by(ano) %>%
    summarise(unemploy_median = median(unemploy), 
              unemploy_min = quantile(unemploy, probs = 0.01),
              unemploy_max = quantile(unemploy, probs = 0.99)) %>%
    ungroup() %>%
    ggplot(aes(x = ano, y=unemploy_median)) +
    geom_line() +
    labs(x = "Ano", y = "Mediana de Desempregados") +
    geom_ribbon(aes(ymin=unemploy_min,ymax=unemploy_max), alpha=.1)
```

17.
```{r}
economics %>%
    mutate(taxa_desem=unemploy/pop) %>%
    gather(group, value, taxa_desem, pce, psavert) %>%
    group_by(group) %>%
    ggplot(aes(x=date,y=value )) +
    geom_line() +
    facet_grid(group~., scales = "free")
```









